import assetsFolder from "../publicfolder"

const newsDemo = [
  { "title": "Cronograma de actividades ExpoDeporte 2023", "description": "Basket, ajedrez, gimnasia artística, yoga, karate, beach voley, fútbol callejero, teqball, skate y muchas disciplinas más. Días de práctica deportiva y recreación, para competir y compartir.", "date": "6/9/2023", "img": `${assetsFolder}/img/news/0.png`, "id": 0, "author": "efra_sk", "fullNote": "Del 16 al 24 de setiembre se desarrollara la ExpoDeporte 2023. A continuación se detalla el cronograma previsto en las distintas localidades..." },

  { "title": "Lanzamiento de ExpoDeporte 2023", "description": "Se conocieron detalles de la nueva edición de este evento deportivo y recreativo que incluye una agenda de actividades a realizarse en varios puntos del departamento explorando diferentes disciplinas.", "date": "5/9/2023", "id": 1, "img": `${assetsFolder}/img/news/1.jfif`, "author": "efra_sk", "fullNote": "Con una gran programación, se espera que la ExpoDeportes 2023 acapare la atención durante las próximas vacaciones de primavera..." },

  { "title": "Lanzamiento de ExpoDeporte 2023", "description": "Un destacado evento que se posiciona y fortalece año a año, que se define a través de una planificada agenda de competencias y actividades desarrolladas en distintos puntos del departamento.", "date": "9/4/2023", "id": 2, "img": `${assetsFolder}/img/news/2.jpeg`, "author": "efra_sk", "fullNote": "Con exhibiciones, competencias, múltiples actividades que exploran y abordan diversas disciplinas, ExpoDeporte se ha posicionado, año a año, como un destacado evento que se desarrolla en distintos puntos del departamento..." },

  { "title": "Impulsando la práctica de Teqball", "description": "Se llevó a cabo en la ciudad de Montevideo el primer campeonato Uruguay Open de Teqball con la participación de los sorianenses Santiago Irigoite y Matías Chopitea.", "date": "16/8/2023", "id": 3, "img": `${assetsFolder}/img/news/3.jpg`, "author": "efra_sk", "fullNote": "Se impulsa la práctica de TeqBall, deporte de pelota que se juega en una mesa curva, combinando elementos de fútbol y tenis de mesa, una disciplina que acapara la atención de varios interesados." },

  { "title": "Sexta fecha del circuito nacional de rugby femenino", "description": "En ese marco, también tuvo lugar el encuentro regional de rugby infantil y juvenil, disputándose en la ciudad de Dolores. De este encuentro, participaron más de 140 niños y adolescentes.", "date": "15/8/2023", "id": 4, "img": `${assetsFolder}/img/news/4.jpg`, "author": "efra_sk", "fullNote": "Se disputó en la ciudad de Dolores la sexta fecha del circuito nacional de rugby femenino juvenil y el encuentro regional de rugby infantil y juvenil." },

  { "title": "Reunión con Comité Olímpico Uruguayo y otras actividades", "description": "Este fin de semana se desarrollaron encuentros abordando diversos asuntos vinculados al deporte con incidencia para nuestro departamento. Por otra parte, se participó del torneo fútbol playa en Rodó.", "date": "7/8/2023", "id": 5, "img": `${assetsFolder}/img/news/5.jpg`, "author": "efra_sk", "fullNote": "Desde la Secretaría de Deportes y Recreación, con la presencia de la directora Noemí Viera, se participó este fin de semana de una reunión en la capital del pais con el Comité Olimpico Uruguayo y las distintas federaciones." },

  { "title": "Inicia Escuela de Skate en Mercedes", "description": "La inauguración de Skate Park habilitó la posibilidad de un nuevo espacio de aprendizaje y encuentro con el lanzamiento de una escuela para participar y compartir momentos practicando la disciplina.", "date": "24/7/2023", "id": 6, "img": `${assetsFolder}/img/news/6.jpg`, "author": "efra_sk", "fullNote": "Tras la inauguración de Skate Park Mercedes, anunciamos el lanzamiento de la Escuela de Skate. Podrán vivir nuevos desafíos y experiencias. En ese marco, los invitamos a participar de este innovador proyecto." },

  { "title": "Pateando la pista: inauguramos Skate Park Mercedes", "description": "obra con incidencia deportiva y recreativa que ha significado una importante inversión impulsada por la Intendencia. Un espacio renovado para disfrutar y preservar.", "date": "24/7/2023", "id": 7, "img": `${assetsFolder}/img/news/7.jpeg`, "author": "efra_sk", "fullNote": "La obra fue inagurada finalmente este domingo 23 de julio, con diversas demostraciones de skate, BMX entre otras, y un cierre final con bandas en vivo. Todo esto, con un ávido marco de público que acompañó la instancia que contó con la presencia del intendente Besozzi y otros referentes del equipo de gobierno." },

  { "title": "Se inaugura Skate Park Mercedes", "description": "Un espacio deportivo y recreativo con gran incidencia para nuestra comunidad. Un proyecto que potencia una visión innovadora en el desarrollo de diversos emprendimientos y planes de gestión.", "date": "19/7/2023", "author": "efra_sk", "id": 8, "img": `${assetsFolder}/img/news/8.jpg`, "fullNote": "La obra será finalmente inaugurada el próximo domingo 23 de julio, a la hora 11 en Manzana 19. En esa ocasión, habrá diversas demostraciones y un cierre final con bandas en vivo." },

  { "title": "Partido amistoso del plantel femenino U2030", "description": "Las integrantes del Proyecto U2030, se enfrentaron amistosamente con su similares de Laureles, en la ciudad de Fray Bentos. Una instancia que promueve la aptitud deportiva y la confraternidad.", "date": "3/7/2023", "author": "efra_sk", "id": 9, "img": `${assetsFolder}/img/news/9.jpg`, "fullNote": "El pasado día sábado, se desarrolló un partido amistoso en la ciudad de Fray Bentos en instalaciones de la cancha de Laureles."}

]

export default newsDemo